In [6]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [7]:
df=pd.read_csv('dhaka_rent.csv')
df.head()


area   rent
0  2000  31500
1  2100  35000
2  2500  41050
3  2250  36100
4  3000  52100

In [8]:
df.shape


(60, 2)

In [9]:
x=df.drop('rent',axis=1)
x
x.head()

area
0  2000
1  2100
2  2500
3  2250
4  3000

In [14]:
y=df['rent']
y.head()

0    31500
1    35000
2    41050
3    36100
4    52100
Name: rent, dtype: int64

In [16]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.30, random_state=42)


In [17]:
xtrain.head()

area
40  2150
4   3000
43  2510
19  2700
34  3000

In [20]:
ytrain.head()

40    34400
4     52100
43    40000
19    47000
34    52200
Name: rent, dtype: int64

In [22]:
from sklearn.linear_model import LinearRegression

In [24]:
reg=LinearRegression()
reg.fit(xtrain,ytrain)
LinearRegression()

LinearRegression()

In [32]:
reg.predict([[1250]])

/Library/anaconda/anaconda3/lib/python3.12/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([15605.05384912])

In [160]:
reg.coef_

array([20.68636687])

In [162]:
reg.intercept_

-10252.90474033673

In [164]:
reg.predict(xtest)

array([31119.82900279, 29051.19231563, 20776.64556701, 53874.83256151,
       41669.87610729, 47668.92250004, 36291.42072068, 26982.55562848,
       33188.46568994, 26982.55562848, 26982.55562848, 33395.32935866,
       33188.46568994, 36291.42072068, 62149.37931013, 21810.96391059,
       45600.28581288, 20776.64556701])

In [166]:
ytest


0     31500
5     32500
36    20200
45    51000
13    40050
54    51000
33    35100
48    25500
12    34500
57    25100
46    30000
50    31000
31    35010
3     36100
52    70500
17    21000
8     48000
6     20000
Name: rent, dtype: int64